"""empty message

Revision ID: 1a2b0f3690c6
Revises: 
Create Date: 2019-04-04 16:35:09.652146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2b0f3690c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=256), nullable=True),
    sa.Column('rating_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questions', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Queries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Queries',
    sa.Column('Id', sa.INTEGER(), server_default=sa.text('nextval(\'"Queries_Id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('questions', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='Queries_pkey')
    )
    op.drop_table('queries')
    op.drop_table('answers')
    # ### end Alembic commands ###
